doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Migrations'
    enable_profiler: false
