FROM php:8.3-fpm

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apt install -y \
    libicu-dev \
    libzip-dev

RUN docker-php-ext-install \
    intl \
    pdo \
    pdo_mysql \
    zip

RUN docker-php-ext-enable opcache

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    echo "short_open_tag=off" >> /usr/local/etc/php/php.ini

COPY --chown=www-data ./ /var/www/html/

WORKDIR /var/www/html

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN composer dump-env prod &&\
    composer i --no-dev --no-scripts
