add_two_positive_numbers:
    path: !php/const UI\Http\Controller\SumTwoPositiveNumbersController::ROUTE
    controller: UI\Http\Controller\SumTwoPositiveNumbersController
    methods: !php/const UI\Http\Controller\SumTwoPositiveNumbersController::METHODS
